### ISSUE TITLE
Usage with interleaved data

### ISSUE THREAD

**Issue by botiapa** [HEnquist/rubato#10]
Hey. I'm new to the world of sample rates, so I probably missed something. I receive 480 bytes (2 channels; 240bytes / channel) of opus decoded samples every x milliseconds. Opus uses 48khz f32 sample format, so I'm trying to resample this to 44.1khz f32. Because the data is interleaved, I also have to reformat it into the format that rubato uses. Unfortunately the resampled data sounds horrible(Not recognizable at all), so I'm probably doing something wrong. I know the input data is correct, because without resampling it, it sound perfect. Here's what I've tried (pseudo-codey):

```
pub fn get_resampler(in_hz: usize, out_hz: usize, ch_in: usize, chunk_size: usize) -> SincFixedIn<f32> {
        let sinc_len = 128;
        let f_cutoff = 0.925914648491266;
        let params = InterpolationParameters {
            sinc_len,
            f_cutoff,
            interpolation: InterpolationType::Linear,
            oversampling_factor: 2048,
            window: WindowFunction::Blackman2,
        };
        SincFixedIn::<f32>::new(
            out_hz as f64 / in_hz as f64,
            params,
            chunk_size,
            ch_in,
        )
}
let resampler = Audio::get_resampler(48000, 44100 as usize, 2 as usize, 480 / 2);

// This function gets called every x milliseconds
pub fn decode_and_queue_packet(&mut self, data: &[u8]) {
        let decoder = self.decoder.as_mut().unwrap();
        
        let mut out = [0f32; 5760*2];
        let read = decoder.decode_float(&data, &mut out, false).unwrap(); // read is always 480

        let buf = self.buffer.as_mut().unwrap(); // Output buffer, this will be read to the OS which will in turn output the sample
        let mut split = [Vec::with_capacity(read), Vec::with_capacity(read)];
        for ch in out[0..read].chunks_exact(2) {
            split[0].push(ch[0]);
            split[1].push(ch[1]);
        }
        let resampled = resampler.process(&split).unwrap();

        for ch in resampled {
            buf.push(ch[0]).unwrap();
            buf.push(ch[1]).unwrap();
        }
}

```
Could you point me in the direction of what I'm doing wrong?
**Feel free to close the issue if you feel like this doesn't belong here.**

**Comment by HEnquist** [comment]
Hi! Let's see if we can sort this out.
First, do you really mean 480 bytes, or should that be 480 samples (240 per channel)?
I don't see anything strange until you write the result to buf:
```
        for ch in resampled {
            buf.push(ch[0]).unwrap();
            buf.push(ch[1]).unwrap();
        }
```
This pushes first the whole vector of left samples onto buf, and then the right samples. Is that what you want? Or do you want to go back to interleaved here?

**Comment by botiapa** [comment]
1. Yeah, I meant 480 samples (240 per channel)
2. Thanks, that was not how I meant to do it. I fixed it with the following code (just for context):
```
for i in 0..resampled[0].len() {
        buf.push(resampled[0][i]).unwrap();
        buf.push(resampled[1][i]).unwrap();
}
```
The sound quality is better, but it still has a lot of artifacts and distortion. I can send some example audio if that helps you identify the problem.

**Comment by HEnquist** [comment]
Yeah a short sample would be useful. 
Do you get ok sound if you go through the interleaved -> non-interleaved -> interleaved conversion, and skip just the resampling step? I mean just changing `let resampled = resampler.process(&split).unwrap();` to something like `let resampled = &split;`.

The output from the resampler will be varying length, are you handling that ok in whatever function receives the buf?

**Comment by botiapa** [comment]
Yes, the conversion between interleaved, and non-interleaved is indeed correct.

The function which reads from the buf is called by windows 50 times a second, and it consumes sample_rate/50 (so for 44.1kh its 44100/50=882). But the resampling function as I observed returns a completely different number. Therefore I tried changing the resampler function to FftFixedIn, but I can't seem to get the ratio right. (Accept 480 samples and return 882 or a fraction of 882) Which resampler should I use for my case?

**Comment by botiapa** [comment]
Here's the example I promised: 
[voice_audio_test.zip -> .mp3 file inside (github doesn't allow audio files for some reason)](https://github.com/HEnquist/rubato/files/5988512/voice_audio_test.zip)

**Comment by HEnquist** [comment]
![resampled](https://user-images.githubusercontent.com/6504678/108099152-88ea9100-7084-11eb-89e8-39efee62f4ff.jpg)
The bad part of the result has chunks of 440 samples, where about 220 are sped up, and the rest are low level noise. 

Checking some numbers.. you get 240 samples per channel per call. At 48kHz that means you get new data every 5 ms.
Then windows reads 882 samples per channel every 20 ms.

The FftFixedIn is probably the best choice, but I think you will have to do some buffering to make sure you match what you get with what windows wants.

**Comment by botiapa** [comment]
Okay, with the help of you analysis I finally managed to work the bug out. 

Thank you very much for your help! The issue is closable.

_Thanks again_
