### ISSUE TITLE
Review and make asserts more helpful

### ISSUE THREAD

**Issue by udoprog** [HEnquist/rubato#14]
So I've recently taken this library for a spin, and one of the things I noted is that it panics in case you give it the wrong kind of parameters.

This is characterized by the asserts, which is not bad in themselves, but some of the asserts are quite nondescript like this one:
https://github.com/HEnquist/rubato/blob/master/src/interpolator_sse.rs#L23

If you backtrack a bit you'll realize that one or more of your input parameters were incorrect (`chunk_size` or `sinc_len`, can't remember from the top of my head).

So the suggestion is:
* It would be helpful if all of the input parameters were validated as early as possible, and that panic messages include instructions of what you did wrong and how to fix it. Generally this can be done with asserts by [adding a custom message as the second parameter](https://doc.rust-lang.org/std/macro.assert.html#examples).
* Review the existing asserts and convert them to errors instead where appropriate. The one above should probably remain (since it guarantees safety of the wrapping API), but an underlying caller could for example validate the parameters. Panics can be quite hard to recover from. With an error the user can decide whether or not to panic.

**Comment by HEnquist** [comment]
Yes that makes sense. 
The particular assert on that line 23 is something I added to catch mistakes when I was writing these parts. A normal user of the library should never run be able to get it, which probably means there is some check missing when creating a new resampler. At that stage it should definitely be an error and not a panic. Or did you create the interpolator directly?

**Comment by HEnquist** [comment]
There have been lots of changes to the library since this was opened. I'm closing this one, but please reopen or create a new issue if needed!
