### ISSUE TITLE
replace Cargo features with runtime detection of CPU capabilities

### ISSUE THREAD

**Issue by Be-ing** [HEnquist/rubato#27]
Instead of picking CPU features at build time with Cargo features, it would be better if the optimal SIMD features could be chosen at runtime. Unfortunately, this is [rather cumbersome](https://raphlinus.github.io/rust/simd/2018/10/19/fearless-simd.html) to implement, but it can be done.

**Comment by HEnquist** [comment]
There is already runtime detection. The Cargo features only determine which instruction sets are available for it to choose from. 
Just build with the (default) `avx` feature on x86_64. On aarch enable the `neon` feature and use a nightly compiler.

**Comment by Be-ing** [comment]
Oh, great! That could be clearer in the documentation. It currently says the avx feature "enables the use of AVX when it’s available". It would help to clarify that binaries built with the `avx` feature can still run on CPUs without AVX.
