### ISSUE TITLE
rubato is not realtime safe

### ISSUE THREAD

**Issue by Be-ing** [HEnquist/rubato#28]
Rubato [allocates](https://github.com/HEnquist/rubato/blob/a2916abd5446cc9ec6e3b56dff793886ee987b70/src/asynchro.rs#L579) its output buffer on every call to Resample::process. I think this should be switched to taking a mutable reference to a buffer. This way, the resamplers with fixed size output buffers could be used in realtime code. The calling code would be responsible for setting the capacity of the Vec in a non-realtime thread before passing it to Rubato. I also suggest adding a `debug_assert!` checking that the Vec's capacity >= the output size.

Also, there are [log macros](https://github.com/HEnquist/rubato/blob/a2916abd5446cc9ec6e3b56dff793886ee987b70/src/asynchro.rs#L424) which allocate Strings in various parts of the code. I suggest to hide these behind a Cargo feature.

[assert_no_alloc](https://docs.rs/assert_no_alloc/) would be useful for verifying that there are no other allocations in the code besides the constructors.

**Comment by HEnquist** [comment]
There is a discussion on a similar topic here: https://github.com/HEnquist/rubato/pull/12
I plan to continue on that when I have some free time. In practice though I have found that allocations are not as bad as their reputation. For example I use Rubato for realtime audio processing [in my DSP application](https://github.com/HEnquist/camilladsp) and the allocations have never caused any problems there. In some prototypes I have even had allocations in the audio callbacks of both Wasapi and CoreAudio without issues.

**Comment by Be-ing** [comment]
> I plan to continue on that when I have some free time.

I would be happy to help. Would you accept a PR putting the logging macro calls behind a Cargo feature?

**Comment by Be-ing** [comment]
> In practice though I have found that allocations are not as bad as their reputation.

I suppose your perspective depends on what kind of application you're writing. I'm writing a musical live performance application so anything I can do to avoid glitches is worthwhile. For context, I'm running with 128 frames/buffer @ 44.1 kHz.

**Comment by HEnquist** [comment]
> > I plan to continue on that when I have some free time.
> 
> I would be happy to help. Would you accept a PR putting the logging macro calls behind a Cargo feature?

I think you can disable logging from your own code by doing as described here: https://docs.rs/log/latest/log/#compile-time-filters

**Comment by HEnquist** [comment]
> > In practice though I have found that allocations are not as bad as their reputation.
> 
> I suppose your perspective depends on what kind of application you're writing. I'm writing a musical live performance application so anything I can do to avoid glitches is worthwhile. For context, I'm running with 128 frames/buffer @ 44.1 kHz.

Ok, I tend to use about 10x more frames per chunk which gives me 10x fewer allocations, and 10x more time available for the ones I have.

**Comment by Be-ing** [comment]
> I think you can disable logging from your own code by doing as described here: https://docs.rs/log/latest/log/#compile-time-filters

I don't think that would work for this case because I use log macros in non-realtime parts of my application.

**Comment by Be-ing** [comment]
Hmm, maybe the `log` compile time filters could work if I split my realtime code into a subcrate... :thinking:

**Comment by HEnquist** [comment]
I started working on an new version for pre-allocating everything. It's only a start so far: https://github.com/HEnquist/rubato/tree/preallocate

I added a trait method `process_into_buffer` that uses pre-allocated buffers for everything. I want to keep the convenient `process` methods, but I'll rewrite them so they are just wrappers for `process_into_buffer`.

**Comment by Be-ing** [comment]
I suggest to keep the API simple by changing the signature of the `process` method rather than adding a new method.

**Comment by HEnquist** [comment]
Changing the `process` method is a breaking change. It also makes the library more difficult to use in applications where the allocations are ok.
I quite like the splitting into one simple and one more advanced method. RustFFT is doing something similar: https://docs.rs/rustfft/latest/rustfft/trait.Fft.html
As long as the documentation is ok there should be no confusion about which one to use.

**Comment by HEnquist** [comment]
@Be-ing Can you take a look at the `preallocate` branch now? I believe it should do what you want.
I marked the logging calls in the critical sections with `#[cfg(debug_assertions)]`. That way they will only be included in debug builds, which I think this is a decent compromise.
Feedback appreciated :)

**Comment by Be-ing** [comment]
Could you make a pull request so we can discuss the code in detail?

**Comment by HEnquist** [comment]
https://github.com/HEnquist/rubato/pull/29

**Comment by Be-ing** [comment]
Fixed by #29
