### ISSUE TITLE
enable neon feature by default

### ISSUE THREAD

**Issue by Be-ing** [HEnquist/rubato#32]
ARM64 intrinsics were stabilized in Rust 1.59. However [is_aarch64_feature_detected won't be stabilized until Rust 1.60](https://github.com/rust-lang/rust/blob/d981633ed6669c6f7b1cb46d1d1a7282e281ca8e/library/std/src/lib.rs#L553). I think after Rust 1.60 is released, the `neon` feature could be enabled by default.

**Comment by HEnquist** [comment]
When I started adding simd both AVX and Neon were experimental. Then putting them behind features was clearly the way to go. But once everything is in stable, I don't think having them optional is providing much value any longer. It's using runtime detection anyway and the simd code is quite small so there is very little impact on the final binary size.
I think I'll take it one step further and enable it all and remove the features.
