### ISSUE TITLE
Resample audio to fit buffer?

### ISSUE THREAD

**Issue by Zerowalker** [HEnquist/rubato#47]
Is it possible to resample audio to fit a dynamic buffer length?
I tried using the sample ratio, but it's not exact and the difference is quite big depending on the scenario.

**Comment by Zerowalker** [comment]
hmm might not actually be the solution to my problem,
i am getting popping whenever i use the resampler, even if the sample_ratio is 1.0.
I thought it was the buffer sizes causing issues on playback, but i then tried just writing the data to disk and the popping is still there.

**Comment by Zerowalker** [comment]
@HEnquist Precisely.
It's meant to stretch the audio to make it fit the playtime in cases where they differ,
it should be quite a small difference if i can do it well and not lag behind a buffer interval.
In that case i think it should be less than 10% (cause the practical difference in playback speed cause of clock differences is actually less than 1%).

I am probably handling this the wrong way as i am new to this.
I currently just remake the resampler all the time, which perhaps causes the issue?

in case you got knowledge on this, i am using WASAPI, and simitating a slower audio rate by reading a bit less than the expected time. So for testing i just read say 9.5ms and pushing out 10ms audio, then sleeping, repeat.

I have tried saving and even playing the buffer i give to the resampler (after interleaving it) and it works fine.
But if i push it through the resampler, than de-interlave the given buffer and play/save that, it gives the pop.
It's likely silence as you say as i know that appears as popping usually when it's extremely short.

**Comment by HEnquist** [comment]
Ok, if you create a new resampler for every chunk, then you will definitely get pops. The first chunk from a resampler always has a little silence at the start, because of the delay introduced by the antialiasing filter. Also, changing the resampling ratio more that a small fraction of a percent is very audible. You want to keep it as constant as possible and only change it to make small adjustments.

What are you actually building? And what determines the desired audio rate?

**Comment by Zerowalker** [comment]
That make sense, i was able to make things somewhat work out when approaching it differently.

// Wall of text explaning my goal and some emulator technicalities, as well as part of code of my current implementation
//  (you have been warned;P)

The goal is to actually be able to use it for an emulator, `bsnes`currently.
But the technical aspect is similar in other emulators, basically the video and audio rate are not the same, but very very close.
so the audio rate is i guess determined by the video rate, or the difference between the two, which i haven't really figured out how to test.

Basically it will emulate a system and display the image locked to vsync.
The audio is created by that system and will start playing when the emulators audio buffer is full for the first time i presume.
And thus the audio is made in real time essentially, so if it's made too slow or too fast compared to how fast it can play it,
things go awry.

So i am thinking of making something that you basically push an audio buffer to,
and it will play it as fast/slow as needed in order to never run out of audio.

I think i have somewhat succeeded in a cheap way.

It looks something like this (using windows `WASAPI`):

```rust
 while done == false {
        loop {
            let sleep_time_ms = 10;
            std::thread::sleep(Duration::from_millis(sleep_time_ms));
            let buf = {
                let mut s = SOUND.lock().unwrap();
                // two channels, so len needs to be buffer_size * 2
                if s.len() < buffer_size * 2 {
                    continue;
                } else {
                    // convert Vec<i16> to Vec<Vec<f64>>
                    sound_length = s.len();
                    let s = s.drain(0..buffer_size * 2 as usize);
                    let s = s.as_slice();
                    let c0: Vec<f64> = s.iter().step_by(2).map(|f| to_float(*f)).collect();
                    let c1: Vec<f64> = s.iter().skip(1).step_by(2).map(|f| to_float(*f)).collect();
                    vec![c0, c1]
                }
            };
            // number of available frames we can push out
            let mut available_frames = unsafe {
                audio_client.0.GetBufferSize().unwrap()
                    - audio_client.0.GetCurrentPadding().unwrap()
            };
            println!(
                "buffer size is: {}, frame_count: {}",
                buf[0].len(),
                available_frames
            );

            let mut resample_ratio = last_resample_ratio;
            // if audio buffer is full (1 second at 48khz) we assume audio is playing too slow
            if available_frames == 48000 {
                resample_ratio = last_resample_ratio + 0.01;
                resampler.set_resample_ratio(resample_ratio).unwrap();
                last_resample_ratio = resample_ratio;
                changes = 0;
            } else if available_frames >= 46000 {
                // we slow down the audio if the buffer is above or equal to 46000 every 15 check
                // cause the change is rather slow and if we do it too fast audio will slow down way too much
                changes += 1;
                if changes == 15 {
                    resample_ratio = last_resample_ratio + 0.001;
                    resampler.set_resample_ratio(resample_ratio).unwrap();
                    last_resample_ratio = resample_ratio;
                    changes = 0;
                }
                high = true;
            } else if available_frames >= 43000 && available_frames <= 45000 {
                // here we check if the previous check was either high or low
                // meaning audio rate was either slowed down or sped up last time.
                // we then expect that to have been too much as it went below/above the expected range.
                // to we try to compensate by slow/speeding up the audio by a larger step in the opposite direction
                changes = 0;
                if high {
                    resample_ratio = last_resample_ratio - 0.008;
                    resampler.set_resample_ratio(resample_ratio).unwrap();
                    last_resample_ratio = resample_ratio;
                    high = false;
                }
                if low {
                    resample_ratio = last_resample_ratio + 0.008;
                    resampler.set_resample_ratio(resample_ratio).unwrap();
                    last_resample_ratio = resample_ratio;
                    low = false;
                }
            } else if available_frames <= 42000 {
                // we speed up the audio if the buffer is below or equal to 42000 every 15 check
                // cause the change is rather slow and if we do it too fast audio will speed up way too much
                low = true;
                changes += 1;
                if changes == 15 {
                    resample_ratio = last_resample_ratio - 0.0003;
                    resampler.set_resample_ratio(resample_ratio).unwrap();
                    last_resample_ratio = resample_ratio;
                    changes = 0;
                }
            } else {
                changes = 0;
            }
            if resample_ratio != 0.0 {
                let percentage = last_resample_ratio - resample_ratio;
                println!(
                    "resample ratio difference : {}, sound length: {}",
                    percentage, sound_length
                );
            }

            let mut waves_out: Vec<Vec<f64>> = vec![vec![], vec![]];

            let buf = &[&buf[0][0..buffer_size], &buf[1][0..buffer_size]];

            let mut tmp = resampler.process(buf, None).unwrap();

            waves_out[0].append(&mut tmp[0]);
            waves_out[1].append(&mut tmp[1]);

            // for testing we write the resamples audio to a wav file
            for v in waves_out[0].iter().interleave(waves_out[1].iter()) {
                ww.write_sample(to_short(*v)).unwrap();
            }

            println!(
                "resampled length: {}, available frames: {}",
                waves_out[0].len(),
                available_frames
            );

            // we set the avaiable frames to equal the length of the resampled audio buffer
            // it needs to always be less or equal to what available_frames is.
            available_frames = waves_out[0].len() as u32;

            // request the audio buffer where to write what's going to be played
            let capture_buffer = render_client.get_buffer(available_frames).unwrap();

            // we convert the Vec<Vec<f64>> to Vec<i16> as that's what the audio buffer expects
            waves_out[0]
                .iter()
                .interleave(waves_out[1].iter())
                .map(|f| to_short(*f))
                .zip(capture_buffer)
                .for_each(|(a, b)| *b = a);

            // we release the buffer (sending it for playback)
            render_client.release_buffer(available_frames, 0).unwrap();
        }
    }
```

**Comment by HEnquist** [comment]
Ok, so now you are making small adjustments to make the average audio rate match the video rate. Looks much better! 

Since this is a realtime task, you should try to avoid allocating vectors inside the loop. I would suggest to create `buf` and `waves_out` before the loop, and reuse the same ones on every iteration. Just create them a little larger than needed and then resize as needed.

**Comment by Zerowalker** [comment]
will try making a fixed buffer.

It seems the adjusments to match the rates doesn't work as well as i had hoped however, but might be my simulation is unrealistic.
i am pushing x amount of samples every y from a separate thread/process , and just sleeping in-between.

**Comment by HEnquist** [comment]
Do you get an uneven and too low rate? Sleep isn't very precise. It's guaranteed to never sleep to little, but it can oversleep by several milliseconds. It's different on different operating systems, iirc it tends to oversleep more on windows than Linux for example.

**Comment by Zerowalker** [comment]
Thanks for showing interest and helping out, much appreciated and i know it's beyond what an issue here should be.
I will be bold and rely more on your knowledge so let me apologies before hand and also say that thanks for you (and other contributors) for making this crate, i don't have enough expertise to say how good/bad it is as i have never used something like this in this way, but the results seems to me to be good quality sound wise, and it doesn't seem to take much performance,
so my naive guess is that it's ranked quite high up on the "resamplers top list"!)

// Now to the questions/feedback stuff aka wall of text

in my test simulation i find it extremely hard to actually make it steady at all,
so if you have some tip there it would be great.

Basically i just read a wav file then push chunks and sleep in order to try to get a certain "rate" but as you say, sleep is not precise, it's probably quite bad on Windows cause it's no difference if i say "sleep 1 ms" or "sleep 1ns",
but i knew from before that sleep is extremely vague but unsure how else to do it.

However i have now updated to using a fixed buffer, i don't fully understand how it works though as you give it the `Vec` and still you use the entire `Vec` to read the data.
Is it cause the capacity is still allocated and it just changed the length?
I haven't tested with/without fixed though which i have to, just to get an idea of the difference in efficiency.

And i have actually been able to put the work into practice, i have modified `bsnes` (but the principle should work anywhere really) so it feeds the audio data into my library and it's resamples and played while trying to steady the rate.

I should probably test how even the rate is as you asked, not sure what the best method of doing that is.
As the data is transferred a bit ugly and checked in the audio loop at difference times as it must also wait for the actual audio playback buffer to be available.
Should i just do an `Instant::now()` every time the resampler receives data, and try averaging it out over a period?


It's a bit ugly how i transfer the data, here's how it looks:

```rust
#[no_mangle]
pub extern "C" fn add_audio(ptr: *const f64, channels: usize, stride: usize, len: usize) -> bool {
    if let Ok(mut s) = audcap::SOUND.lock() {
        for (i, row) in (0..(channels * stride)).step_by(stride).enumerate() {
            let t = unsafe { std::slice::from_raw_parts(ptr.offset(row as isize), len) };

            if s.len() < i + 1 {
                s.push(Vec::new());
            }
            s[i].extend_from_slice(t);
        }
        if let Ok(t) = audio_thread().inner.lock() {
            !t.as_ref().map(|f| f.is_finished()).unwrap_or(true)
        } else {
            true
        }
    } else {
        false
    }
}
```
where `SOUND` is just a:
```rust
lazy_static::lazy_static! {
  pub static ref SOUND: Mutex<Vec<Vec<f64>>> =Mutex::new(Vec::new());
}
```
which feels like a very ugly hack, even tough it seems to work.


The source data is a 2D array but with the channels and samples swapped so i have to swap it before sending,
but perhaps there's a way to work with it like it is through te resampler directly, as you know the inner workings?
the source buffer is: `double samples[65536][8];`
which i swap to `double samples[8][65536]`  (you can ignore the size and channels, it's just the max, but you get the idea).


Another question (in my wall of text, not expecting you to read or even answer all this so don't worry;P)
Is it possible to pitch correct when resampling, i believe that's what it's called, so it doesn't sound speedup/down,
even though it should (in best cases if my stuff works) be within less than 1% of the original rate.

**Comment by HEnquist** [comment]
> in my test simulation i find it extremely hard to actually make it steady at all, so if you have some tip there it would be great.
> 
> Basically i just read a wav file then push chunks and sleep in order to try to get a certain "rate" but as you say, sleep is not precise, it's probably quite bad on Windows cause it's no difference if i say "sleep 1 ms" or "sleep 1ns", but i knew from before that sleep is extremely vague but unsure how else to do it.
> 

There are a few ways. The first and simplest one is simply to send larger chunks so you can sleep for longer. It will still be inaccurate, but the relative error shrinks. Then this can be improved by checking how long it really did oversleep, and then shortening the next sleep call by that amount. If this still isn't good enough, you need help from the operating system. Something like this: https://docs.microsoft.com/en-us/windows/win32/api/threadpoollegacyapiset/nf-threadpoollegacyapiset-createtimerqueue
But maybe this is getting a bit too much for a simulation..

> However i have now updated to using a fixed buffer, i don't fully understand how it works though as you give it the `Vec` and still you use the entire `Vec` to read the data. Is it cause the capacity is still allocated and it just changed the length? I haven't tested with/without fixed though which i have to, just to get an idea of the difference in efficiency.
> 

Yes it resizes the Vec as needed. A vec has a length, which is the current number of elements it stores, and a capacity, which is the size of the backing storage. Resizing doesn't touch the capacity, as long as the new length <= capacity.

> And i have actually been able to put the work into practice, i have modified `bsnes` (but the principle should work anywhere really) so it feeds the audio data into my library and it's resamples and played while trying to steady the rate.
 
> I should probably test how even the rate is as you asked, not sure what the best method of doing that is. As the data is transferred a bit ugly and checked in the audio loop at difference times as it must also wait for the actual audio playback buffer to be available. Should i just do an `Instant::now()` every time the resampler receives data, and try averaging it out over a period?
> 

Yes, something like that. Try averaging over a few seconds.

> It's a bit ugly how i transfer the data, here's how it looks:
> 
> ```rust
> #[no_mangle]
> pub extern "C" fn add_audio(ptr: *const f64, channels: usize, stride: usize, len: usize) -> bool {
>     if let Ok(mut s) = audcap::SOUND.lock() {
>         for (i, row) in (0..(channels * stride)).step_by(stride).enumerate() {
>             let t = unsafe { std::slice::from_raw_parts(ptr.offset(row as isize), len) };
> 
>             if s.len() < i + 1 {
>                 s.push(Vec::new());
>             }
>             s[i].extend_from_slice(t);
>         }
>         if let Ok(t) = audio_thread().inner.lock() {
>             !t.as_ref().map(|f| f.is_finished()).unwrap_or(true)
>         } else {
>             true
>         }
>     } else {
>         false
>     }
> }
> ```
> 
> where `SOUND` is just a:
> 
> ```rust
> lazy_static::lazy_static! {
>   pub static ref SOUND: Mutex<Vec<Vec<f64>>> =Mutex::new(Vec::new());
> }
> ```
> 
> which feels like a very ugly hack, even tough it seems to work.
> 

A bit hacky yes :) But it tends to get a bit ugly when you need callbacks from C.
See if you can use a channel instead to pass data. Crossbeam-channel is quite nice: https://docs.rs/crossbeam-channel/latest/crossbeam_channel/

> The source data is a 2D array but with the channels and samples swapped so i have to swap it before sending, but perhaps there's a way to work with it like it is through te resampler directly, as you know the inner workings? the source buffer is: `double samples[65536][8];` which i swap to `double samples[8][65536]` (you can ignore the size and channels, it's just the max, but you get the idea).
> 

The resampler needs the swap. You might be able to use the transpose crate to do it quickly; https://crates.io/crates/transpose

> Another question (in my wall of text, not expecting you to read or even answer all this so don't worry;P) Is it possible to pitch correct when resampling, i believe that's what it's called, so it doesn't sound speedup/down, even though it should (in best cases if my stuff works) be within less than 1% of the original rate.

That is time-stretching and not resampling! The only crate for that I know is this: https://crates.io/crates/ness_stretch, but I haven't used it.

**Comment by Zerowalker** [comment]
Thanks so much for the feedback:)

I have made a ton of adjustments, changed to using channels, averaging buffer time over a period of x etc.
it works extremely well, the only time it "breaks" is when there's a sudden drop, which occurs at times for some odd reason,
but it's from the source (bsnes) side, and to take account one would need to always have a high buffer.

Been testing it over long periods when playing and i can't really tell that any difference in quality,
only time i noticed it sounded crap when testing i belive was when having a low `sinc_len` and `chunk_size`.
But if those are 256 or more (along with BlackmanHarris2 and Cubic), it seems to be "flawless" as far as i can tell, not sure what determines how "good" the resampling can be or not?

> The resampler needs the swap. You might be able to use the transpose crate to do it quickly; https://crates.io/crates/transpose

I made my own one using `AVX`, it's faster in benchmarks but not sure if it's actually faster in practice,
as i believe there's some delay when starting up the `AVX` circuit, it's super fast on manual and `AVX` nevertheless though:P

Here's how it looks if you are interested:)

```rust
macro_rules! load_permute_store {
    ($x:expr,$y:expr,$z:expr) => {{
        let ymm0 = _mm256_castpd128_pd256(_mm_load_pd($x.get_unchecked($y).as_ptr()));
        let ymm0 = _mm256_insertf128_pd::<1>(ymm0, _mm_load_pd($x.get_unchecked($y + 1).as_ptr()));

        let ymm1 = _mm256_permute4x64_pd::<0b11_01_10_00>(ymm0);
        let lo = _mm256_castpd256_pd128(ymm1);
        _mm_storeu_pd($z.get_unchecked_mut(0).get_unchecked_mut($y), lo);
        let hi = _mm256_extractf128_pd::<1>(ymm1);
        _mm_storeu_pd($z.get_unchecked_mut(1).get_unchecked_mut($y), hi);
    }};
}

// swaps [samples][channels] to [channels][samples] (8 channels -> 2 channels), must be /16 aligned
pub unsafe fn buffer_transpose_avx(samples: &[[f64; 8]]) -> [Vec<f64>; 2] {
    let mut swapped_samples: [Vec<f64>; 2] = [vec![0.0; samples.len()], vec![0.0; samples.len()]];

    let mut x_idx = 0;
    for _ in 0..samples.len() / 16 {
        load_permute_store!(samples, x_idx, swapped_samples);
        x_idx += 2;
        load_permute_store!(samples, x_idx, swapped_samples);
        x_idx += 2;
        load_permute_store!(samples, x_idx, swapped_samples);
        x_idx += 2;
        load_permute_store!(samples, x_idx, swapped_samples);
        x_idx += 2;
        load_permute_store!(samples, x_idx, swapped_samples);
        x_idx += 2;
        load_permute_store!(samples, x_idx, swapped_samples);
        x_idx += 2;
        load_permute_store!(samples, x_idx, swapped_samples);
        x_idx += 2;
        load_permute_store!(samples, x_idx, swapped_samples);
        x_idx += 2;
    }
    swapped_samples
}
```

> That is time-stretching and not resampling! The only crate for that I know is this: https://crates.io/crates/ness_stretch, but I haven't used it.

Oh, i actually didn't know `time-stretching` was a real term, and that `resampling` just included both changing samplerate and also anything that alters the actual time, i do here.
Feels kinda odd, as one can just do free "time resampling" otherwise by just setting a different samplerate on the audio (if allowed), though of course you are limited by integers.

But okay so time-stretching includes both resampling with a different ratio + pitch correction?
If it's not available in this crate i will let it be as i can't hear the difference anyhow as it's currently at max 0.004% difference in speed.
And this crate has worked wonders and it's really simple to work with, even for someone that lacks a lot of knowledge on how it works:)

**Comment by Zerowalker** [comment]
what decides the quality?
i am trying to figure out what sizes to use,
from your examples this seems to be the highest quality (i take that as any increase does miniscule improvements).
```rust
  InterpolationParameters {
    sinc_len: 256,
    f_cutoff: 0.9473371669037001,
    interpolation: InterpolationType::Cubic,
    oversampling_factor: 256,
    window: WindowFunction::BlackmanHarris2,
},
```
 How does the `chunk_size` play into this?
 As i assume the `sinc_len` is limited to the amount of samples available, so it can't exceed it?

**Comment by HEnquist** [comment]
The quality is mainly determined by the oversampling factor, and if you select cubic or linear interpolation. 
The `sinc_len` affects how high you can set `f_cutoff`. A long sinc means you get a sharp roll-off of the anti-aliasing filter, so you can put it closer to 1.0 without getting ugly aliasing in the output. If you can live with a having the filter roll off earlier, you can use a lower value for `sinc_len` and save some cpu time.
The example you quoted gives very good results. Increasing the oversampling ratio more gives very little improvement. The f_cutoff is already quite close to 1 and gives a cutoff of about 20.8 kHz at 44.1 kHz for example, not far from the 22.05kHz limit.

The chunksize doesn't affect the quality, you just set it to whatever your application needs. You can have a longer sinc_len than chunksize. It does have some impact on efficiency. I haven't measured but I would expect that making the chunksize very small will slow it down. Stay over 100 or so and you should be ok. Or better, measure it :)

**Comment by Zerowalker** [comment]
hmm, don't quite understand the `cutoff` but it's just my lack of knowledge in how this all works.
but if `f_cutoff` and `sinc_len` are opposite forces, which one actually matters most in terms of pure quality?
As i take it 1.0 is ideal, and you want enough `sinc_len` to make the roll-off as sharp as possible,
is there such a point?
Like if you have 48khz and a `sinc_len` of 1024 the roll off is "X" which means it's inaudible so the `f_cutoff` can be 1.0 as making it lower changes nothing in practice.

And does the actual sample rate matter here?
I usually have 48khz which is (as far as i know) above what human can hear, as even 44.1khz is (but it's close to the max with some margin i believe).
So will 48khz have an easier time cause it's "oversampled" a bit already, or does it not play a role?

surprised `chunksize` doesn't matter, was sure limiting the amount of samples it can work with would impact what can be done.
I have used it with as low as 48 in real time without any performance difference in practice compares to 432 which is my second goto as i can work with 10ms (480 samples) and realistically not having to worry about it resampling it from 432 to > 480.
Though thinking about it i don't think it matters as i still check against `output_frames_max()` so will need to do some testing there.
But performance difference at least seems to be very low in real time, will try in a benchmark out of interest:)

**Comment by HEnquist** [comment]
Ideally the cutoff would be samplerate/2, but that would require an infinitely sharp filter. And that would require `sinc_len` to be infinity. Obviously we can't have an infinitely long filter so we need to compromise. So we make it a finite length, and apply a window function to make sure it goes to zero at the ends. This makes the filter less sharp. But we still need a high attenuation at frequencies >= samplerate/2. The only way to get that is to make the less steep filter start rolling off earlier. The example above, with length 256 and cutoff 0.947.. means it starts rolling off at 20880 Hz (instead of the ideal 22049.99999999). This makes it attenuate well at 22050 Hz and above.
The best cutoff for a given length depends on which window function is used. For BlackmanHarris2, you can get a good estimate with this formula: ```let cutoff = 0.4f32.powf(16.0 / sinc_len as f32)```
You are correct that you can allow an earlier roll-off at 48 kHz since you get a few more kHz to spare than at 44.1kHz. In practice though, only young children can hear 20 kHz. It drops with age and adults normally have their limit quite a bit lower, so most likely you can get away with a cutoff frequency as low as 17 or 18 kHz without getting any complaints. 

It keeps an internal buffer to make sure it always has enough samples to work with for the given sinc_len. That's why the chunksize doesn't matter.

**Comment by HEnquist** [comment]
I'm adding a helper function for calculating a suitable cutoff. See https://github.com/HEnquist/rubato/blob/calc_cutoff_helper/src/windows.rs#L101
I will include it in the next release.

**Comment by Zerowalker** [comment]
Very sorry for the late response!

Oh i think i get a better grasp of it. But i clearly lack the understanding of how it all works so need to read up on that.
But i get that perfection is impossible mathematically so you have to do tradeoffs, and depending on the window function you can get "transparent" results differently.

Oh wait so the internal buffer doesn't add a delay, but it makes it have less to work with on the first times i guess?
as it can't have enough in the internal buffer until you actually has given enough.

I thought it had to work per-chunk, if i understood what you meant then that explains that:)

> I'm adding a helper function for calculating a suitable cutoff. See https://github.com/HEnquist/rubato/blob/calc_cutoff_helper/src/windows.rs#L101
> I will include it in the next release.

Oh, now that's much appreciated and very convenient!
Out of interest where did you reach the values provided there?
I get that one was based on the formula you gave in the previous answer (but how did you even reach that?).

Perhaps it's "obvious" once get a clear understanding of how it all works though.

Thanks as always, your enthusiasm is admirable:)

**Comment by HEnquist** [comment]
There is always a delay, of sinc_len/2 frames. That's actually another reason one might want to keep the sinc_len down. It's basically just convolution. If you convolve a 1000 element vector (the audio data) with another 100 element vector (the sinc) you can calculate 900 elements without the small vector going outside the large one. Think of it as sliding a 100mm ruler over a 1000mm one. If the small one isn't allowed to stick outside long one, you can move it at most 900mm from one end to the other.

The cutoff function uses fitted formulas to estimate the cutoff value. The fitting is done with this script: https://github.com/HEnquist/rubato/blob/calc_cutoff_helper/utils/cutoff_fit_cubic.py
The old formula was done by trial and error. The new one gives much better approximations.

**Comment by Zerowalker** [comment]
Ah, so it ends up like a "buffer" in the that sense, that make sense, felt weird if there as not much consequence,
rarely you get something without a tradeoff so to speak.

I tried the script and if it seems very straightforward, i take it you want the top graph to be as high as possible,
and you have to decide how much diminishing returns you are willing to take to get an improvement.

What's the "Power 2" stuff though?

**Comment by HEnquist** [comment]
Closing as part of spring cleaning :)
Please reopen if needed.
