### ISSUE TITLE
Real-time: Write output into `AsMut<[T]>` instead of `Vec<T>`

### ISSUE THREAD

**Issue by uklotzde** [HEnquist/rubato#49]
The real-time API is not as generic as it ought to be. The output buffer should be a slice of (mutable) references instead of a slice of vectors.

### Actual

```rust
    fn process_into_buffer<V: AsRef<[T]>>(
        &mut self,
        wave_in: &[V],
        wave_out: &mut [Vec<T>],
        active_channels_mask: Option<&[bool]>,
    ) -> ResampleResult<()>;
```

### Desired

```rust
    fn process_into_buffer<Vin: AsRef<[T]>, Vout: AsMut<[T]>>(
        &mut self,
        wave_in: &[Vin],
        wave_out: &mut [Vout],
        active_channels_mask: Option<&[bool]>,
    ) -> ResampleResult<()>;
```

If the size of the output buffers is insufficient then the invocation should return with an error.

This is the expected signature required for a generic audio processing graph. Currently resampling requires a separate buffer and copying the results.

Typically you would use a crate like [rsor](https://docs.rs/rsor/latest/rsor/) for composing those slices of (mutable) references.

**Comment by HEnquist** [comment]
This makes sense, I will look into it.
Currently the number of written frames is returned by resizing the Vecs, and this information should still be provided. I would go for a slightly modified version where it's included in the ResampleResult:
```
    fn process_into_buffer<Vin: AsRef<[T]>, Vout: AsMut<[T]>>(
        &mut self,
        wave_in: &[Vin],
        wave_out: &mut [Vout],
        active_channels_mask: Option<&[bool]>,
    ) -> ResampleResult<usize>;
```
An alternative would be to force the output buffer to be the exact right length, but I feel that could get a bit annoying.

**Comment by uklotzde** [comment]
Thanks for considering my proposal!

> An alternative would be to force the output buffer to be the exact right length, but I feel that could get a bit annoying.

The required buffer size should probably be returned as an `Err`, e.g. `InsufficientOutputBufferSize`. Returning `Ok` if the size of the output buffer is insufficient and the invocation actually didn't perform the requested operation is dangerous.

The implementation should be straightforward. But it is a breaking API change, not a big deal for 0.x hopefully.

**Comment by uklotzde** [comment]
I could try to implement it once we agreed on the API.

**Comment by uklotzde** [comment]
We should return the actual size in either case, i.e. as `Ok` and as `Err`.

**Comment by HEnquist** [comment]
this has been released now
