### ISSUE TITLE
Remove initial silence?

### ISSUE THREAD

**Issue by danigb** [HEnquist/rubato#53]
Hello 👋 

Thanks a lot for this awesome library! 🎉 

I have a question: is it possible to remove, somehow, the initial silence created by the anti-aliasing filters?

Thanks in advance!

**Comment by HEnquist** [comment]
The silence is there to make sure the resampled data starts "nicely", without any spikes or such. You could cut off the silence afterwards, just trim it off the start of the first chunk. The issue is to know how many frames to remove. I could add a method to get the initial delay in frames, would that help?

The alternative is to add an option to not include the delay on the first chunk at all. This might be useful, but it would make the already complicated initialisation of the resampler even worse..

**Comment by danigb** [comment]
Yes, I've tried to trim of the first chunk, but I faced that problem about how much to cut. Exposing the initial delay in samples would definitely help.

Thanks a lot!

**Comment by HEnquist** [comment]
See https://github.com/HEnquist/rubato/issues/54

**Comment by HEnquist** [comment]
> EDIT: BTW, I've found the silence to be proportional to chunk size. I guess that's how it works. If so, maybe we should mention that on the documentation.

That's how it works for the FFT resampler. For the others you have more direct control via the since length.

**Comment by obsoleszenz** [comment]
I'm not sure if I'm currently hitting this too, but i'm currently trying to write some tests against my dj audio engine which uses rubato and was suprised to see a ramping on the samples even if my own ramping was disabled on the first frame. Is this really needed if i take care of ramping up the first chunk myself? Is this ramping happening also when changing the tempo?  Or more general asked, when is this ramping happening and how?

**Comment by HEnquist** [comment]
What ramping do you mean? Amplitude? That's only on the first chunk and you can trim it off. Use the new methods in https://github.com/HEnquist/rubato/issues/54 to know how much to trim then.

**Comment by HEnquist** [comment]
It's a delay to make space for the pre-ringing of the sinc AA filter. In most cases you can safely trim it off.

**Comment by yamadapc** [comment]
Would there be latency added from the FFT? (e.g.: `1/4 * BLOCK_SIZE`)

**Comment by HEnquist** [comment]
You mean for the FFT resampler? Yes it also has an anti aliasing filter with a similar pre-ringing. The length is half the FFT size. The new methods for getting the delay size works here too. I will publish the next version soon, just busy with other stuff.

**Comment by HEnquist** [comment]
The new version 0.13 was just released, should help here.

**Comment by danigb** [comment]
Thanks a lot @HEnquist  👍
