### ISSUE TITLE
Method for getting delay

### ISSUE THREAD

**Issue by HEnquist** [HEnquist/rubato#54]
The anti-aliasing filters introduce a delay. Presently there is no way to know the delay of a resampler. Add a trait method to get this information.

**Comment by obsoleszenz** [comment]
This would be quite helpful. I'm currently trying to write tests against an audio engine that uses rubato and this somehow suprised me. As even if i'm "resampling" from `sample_rate_in == sample_rate_out` this ramping/delay seems to happen.

**Comment by HEnquist** [comment]
Implemented  in https://github.com/HEnquist/rubato/pull/45
