### ISSUE TITLE
Specify Framecount of Input and Output

### ISSUE THREAD

**Issue by stexa** [HEnquist/rubato#56]
Is there a way to resample while not changing the number of frames?
I know that resampling is changing the amount of samples present in the buffer, but I have to use an audio process that only accepts one specific sample rate / frame size config.

**Comment by HEnquist** [comment]
You mean resampling for example 44.1kHz in 1024 frame chunks, to 96kHz also in (2.17 times more) 1024 frame chunks?

**Comment by stexa** [comment]
yes exactly

**Comment by HEnquist** [comment]
Ok so then each call to processa chunk would need to produce from zero to several output chunks, depending on the resampling ratio). My example of 44.1-> 96 would produce two most of the time, and three once in a while.
This functionality isn't available in te library, but it should be reasonably straightforward to work around this. I would use a FixedIn resampler and feed it the input chunks directly. Then I would store the output in an intermediate buffer, and read from that buffer to produce as many output chunks as there is data for.
It would also work to use a FixedOut resampler and keep the buffer in front of it, not sure which is easier (probably quite similar).

**Comment by stexa** [comment]
Yep thank you!
Probably this is the way to deal with different number of frames:
https://hal.science/hal-02158912
