### ISSUE TITLE
FtfFixedInOut resampler expects wrong number of frames

### ISSUE THREAD

**Issue by Unbreathable** [HEnquist/rubato#57]
Hello!
I've been coding a voice recorder using this amazing library. I've now ran into a problem I've been trying to fix for ours and just think that it must be something to do with the library, since I just don't see any way for me to fix it.
I'm using cpal to record data from the microphone at a buffer size of 1024 in a stereo channel, since microphones usually have a sample rate of 44100 hz instead of 48000 hz (the sample rate I need to encode with opus), I used this resampler library like this:

```rust
let mut resampler = FftFixedInOut::<f64>::new(
    sample_rate as usize,
    opus_sample_rate as usize,
    1024,
    channels as usize,
).unwrap();
```

Every time I try to pass my 1024 frames per channel into the library it just says "Wrong number of frames 1024 in input channel 0, expected 1029".

I also tried measuring the size of the vectors like this:
```rust
// Convert into seperate channels
let channels = extract_channels(data, channels as usize);

println!("channels: {:?}", channels.len());
println!("samples in 0: {:?}", channels[0].len());
println!("samples in 1: {:?}", channels[1].len());

// Resample
let resampled = resampler.process(&channels, None).unwrap();
```

Then I get the following output:
```
channels: 2
samples in 0: 1024
samples in 1: 1024
thread 'cpal_alsa_in' panicked at 'called `Result::unwrap()` on an `Err` value: Wrong number of frames 1024 in input channel 0, expected 1029', src/record.rs:57:64
```

I don't know why this happens, but I'm kind of new to rust, so I'm sorry if I'm getting something wrong here.

**Comment by HEnquist** [comment]
This is not a bug, rather a limitation of the FixedInOut resampler. 44.1 -> 48 kHz is a resampling ratio of 160/147, meaning that 147 input samples become 160 output samples. The input and output lengths must be multiples of those numbers and it gives you the closest match it can to what you request. Here that is 7*149=1029 which becomes 7*160=1120 on the output.

If you need 1024 both in and out, then you need to use a FixedIn and buffer whatever it outputs and chop it into 1024 long chunks yourself. Or you can use a FixedOut and buffer on the input side, it's the same thing just different order :)

**Comment by Unbreathable** [comment]
Alright, thanks for telling me and also thanks for the quick response. This library is amazing and so much simpler than anything else on crates.io, thanks for making it!
