### ISSUE TITLE
Sound gets cut off at the end when resampling to a lower sample rate with FftFixedIn?

### ISSUE THREAD

**Issue by matidfk** [HEnquist/rubato#58]
I'm not sure if I'm misusing the library or something, but from my use case, when resmapling eg. from 48kHz to 44.1kHz, the sample gets cut off at the end. And I think this seems to correspond with the length of the silence at the start obtained via output_delay().

**Comment by matidfk** [comment]
Ok after a bit of fiddling around with the settings when initializing the resampler, it turns out the issue was the sub_chunks parameter. I have used 2 for this as per the examples, but changing it to something like 8 resolves this issue

**Comment by HEnquist** [comment]
Yes it's connected with the delay. You need to feed the resampler some silence to flush the last samples out. It will be easier in the next version: https://github.com/HEnquist/rubato/pull/45/commits/08e1d08955627ad5cee33de18783952ebda4e2d9

Using more subchunks gives you a smaller delay. It still cuts, just less.
