### ISSUE TITLE
`output_buffer_allocate` should be zeroed instead of `Vec::with_capacity`

### ISSUE THREAD

**Issue by topia** [HEnquist/rubato#60]
From rubato-0.13.0, `process_into_buffer` consumes slices instead of vectors.
I don't have any opinion about this, but I used `output_buffer_allocate` to allocate the output buffer, it panicked with `insufficient output buffer size 0` and I can't understand why for a few minutes.

**Comment by topia** [comment]
After more research, `output_buffer_allocate` is not worked as expected.
With my configuration, `nbr_channels` is `2` and `output_frames_max` is `17`, `output_buffer_allocate` makes a vec as same as `vec![Vec::with_capacity(0), Vec::with_capacity(17)]`. I can't understand why.

**Comment by topia** [comment]
I completely understood the capacity problem (second one).
`vec![elem; count]` [expands](https://github.com/rust-lang/rust/blob/70e04bd88d85cab8ed110ace5a278fab106d0ef5/library/alloc/src/macros.rs#L47) to `vec::from_elem(elem, count)`, finally elem [wrapped](https://github.com/rust-lang/rust/blob/70e04bd88d85cab8ed110ace5a278fab106d0ef5/library/alloc/src/vec/spec_from_elem.rs#L16) by `ExtendElement(elem)`, and passed to `extend_with`.
ExtendElement [returns cloned one except last](https://github.com/rust-lang/rust/blob/70e04bd88d85cab8ed110ace5a278fab106d0ef5/library/alloc/src/vec/mod.rs#L2478-L2486).
Finally, Vec::clone ignores the original capacity.

**Comment by HEnquist** [comment]
Thanks for reporting this! I'll fix and release 0.13.1 asap.

**Comment by HEnquist** [comment]
See https://github.com/HEnquist/rubato/pull/62

**Comment by topia** [comment]
Hmm, by the way, I **think** we can pass the result of `output_buffer_allocate` into `process_into_buffer` as arg without additional modification.

**Comment by HEnquist** [comment]
It works as long as it's filled to at least the needed length. An empty one won't be accepted.
There is a check here, that all resampler types use: https://github.com/HEnquist/rubato/blob/master/src/lib.rs#L625

**Comment by topia** [comment]
Yes, I'm sure it works if `output_buffer_allocate` fills with zeros. I couldn't realize if `output_buffer_allocate` will fill or not, from your comment. Sorry for my poor English.

**Comment by HEnquist** [comment]
Fix merged, new version published!
