### ISSUE TITLE
`output_frames_max` returns an incorrect upper bound for at least `FftFixedIn`

### ISSUE THREAD

**Issue by AlexTMjugador** [HEnquist/rubato#63]
As described in https://github.com/HEnquist/rubato/pull/62#issuecomment-1584503583, `output_frames_max` returns an incorrect value for `FftFixedIn` and maybe other resamplers with a variable number of output frames. Given that this violates the API design principle of least surprise, I think that the return value should be fixed, or if not possible due to the how the resampler works, an error should be returned.

## Minimal reproducible example

```rust
use rubato::{FftFixedIn, Resampler};

fn main() {
    let audio_data = vec![0.0_f32; 44100 * 5];

    let mut resampler = FftFixedIn::<f32>::new(44100, 40000, 512, 2, 1).unwrap();

    // The following buffer could be more concisely created with resampler.output_buffer_allocate(),
    // but it doesn't work: https://github.com/HEnquist/rubato/pull/62
    let mut output_buf = vec![vec![0.0; resampler.output_frames_max()]; resampler.nbr_channels()];

    for chunk in audio_data.chunks(512) {
        resampler
            .process_into_buffer(&[chunk], &mut output_buf, None)
            .expect("Unexpected resampling error");
    }
}
```

## Output

```
thread 'main' panicked at 'Unexpected resampling error: Insufficient buffer size 512 for output channel 0, expected 800', src/main.rs:15:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1a5f8bce74ee432f7cc3aa131bc3d6920e06de10/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/1a5f8bce74ee432f7cc3aa131bc3d6920e06de10/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/1a5f8bce74ee432f7cc3aa131bc3d6920e06de10/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::expect
             at /rustc/1a5f8bce74ee432f7cc3aa131bc3d6920e06de10/library/core/src/result.rs:1033:23
   4: rubato_issue_repro::main
             at ./src/main.rs:13:9
   5: core::ops::function::FnOnce::call_once
             at /rustc/1a5f8bce74ee432f7cc3aa131bc3d6920e06de10/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## State of the stack frame where the variables that trigger the validation error are set

![Stack frame state](https://github.com/HEnquist/rubato/assets/7822554/c6da95e0-4b11-4df9-a516-8549a1a3dcdb)

**Comment by HEnquist** [comment]
Thanks! I'll take a look asap.

**Comment by HEnquist** [comment]
The max output length was calculated incorrectly for FftFixedIn, should be fixed by https://github.com/HEnquist/rubato/commit/a7ad2c146af9dbe9ac818a8fc4acc999d9d9fb93
It works with the example above now, if chunks() is changed to chunks_exact(). Otherwise it panics on the last partial chunk. Can you check that it works for you?

**Comment by AlexTMjugador** [comment]
As expected, it works when using `chunks_exact`. Thank you a bunch! :heart:

**Comment by HEnquist** [comment]
Fix merged, new version published!
