### ISSUE TITLE
Using this library for Clock Drift correction

### ISSUE THREAD

**Issue by dscso** [HEnquist/rubato#64]
I am building an audio transmission system over Ethernet in Rust. I have a audio stream with 64 sample buffers (so quite small) and for clock drift correction I have to add or remove a sample from time to time.

For now I am just removing or adding a sample and smooth using linear interpolation, so quite an easy approach. It works quite good and is not noticeable as long as you don't play back a high frequency (1KHz) Sinus but I still want to get rid of these artifacts.

Is this library suited for this purpose? I tried something using the FFT sampler:
```rust
let mut resampler = rubato::FftFixedIn::<f32>::new(
        48000,
        48000,
        64,
        64,
        2,
    );
```
but I am not able to change the output sample rate from time to time. To reinstantiate the sampler also doesn't work, as this generates artifacts.

**Comment by HEnquist** [comment]
Yes this is one of the main purposes of this library. You will need to use on of the asynchronous resampler types for this though. FftFixedIn is synhronous so it can't be adjusted.
Try for example SincFixedIn of SincFixedOut. Then you monitor your drift and call `set_resample_ratio_relative()` once in a while to keep them in sync.

**Comment by dscso** [comment]
thank you very much for the fast response :) I got it working!
