### ISSUE TITLE
Resampling without adjusting pitch

### ISSUE THREAD

**Issue by zkldi** [HEnquist/rubato#70]
Hi, is there a way to use this library to resample audio without changing the pitch of the played back audio?

I.e. if I have a device that is set to output sound at 48000 and I set the resample ratio to 1.5, I want the audio to play back 1.5x as fast but with the same pitch as it was on 1.0.

**Comment by HEnquist** [comment]
That is not possible with this library. You will need to use some pitch shifting algorithm. I have not tested any, but I have seen these two on crates.io:
https://crates.io/crates/pitch_shift
https://crates.io/crates/ness_stretch

**Comment by zkldi** [comment]
Hi, no problem. Would it be planned to add this functionality to this library at some point? I figure it would be convenient for a lot of people.

If not I'll go ahead and close this issue!

**Comment by HEnquist** [comment]
That is a very different concept than sample rate conversion. I don't plan to add it here.
