### ISSUE TITLE
Is there a way to work with u8/u16 buffer type instead of f64 ?

### ISSUE THREAD

**Issue by MatthD** [HEnquist/rubato#71]
Is is possible to work with u16/u8 buffer data ?

```rust
let mut resampler=  FastFixedIn::<u16>::new(f_ratio, 1.1, PolynomialDegree::Septic, 1024, output_channels as usize).unwrap();
```

Seems to lead to issue

**Comment by HEnquist** [comment]
This is not supported at the moment. You need to convert your integer samples to f32 or f64 before resampling. 

It will be supported in a future version, but I don't dare to make any estimates for when that will be ready.

**Comment by MatthD** [comment]
Thank you for your answer, very clear ! ;)

**Comment by HEnquist** [comment]
You can see some early experimentation for this here: https://github.com/HEnquist/rubato/tree/adapter
It uses the new (and also experimental) audioadapter crate, https://github.com/HEnquist/audioadapter-rs, to be generic over buffer layout and sample format.

**Comment by MatthD** [comment]
Sorry to have reopened it ,

I am facing issue working with file that I converted first with sox as your example but to `signed-integer -b 16` (to simulate what we have with WebRTC in our codebase for example)
You example perfectly work for f64 data but trying to adapt to i16 lead me to issues .
I suppose  I needed to [changes bytes per sample ](https://github.com/HEnquist/rubato/blob/master/examples/fastfixedin_ramp64.rs#L33) but it panic then

I will try your adapter but if you have suggestion on this int16 issue I am facing I will take it :D

**Comment by HEnquist** [comment]
Did you try try to adapt the example from master, or from the adapter branch?
Can you put your modified code somewhere so I can see what you have done?

**Comment by MatthD** [comment]
Sure ! 

So my first idea was to just adapt as small as the example :

```rust
pub fn buffer_to_vecs<R: Read>(input_buffer: &mut R, channels: usize) -> Vec<Vec<f64>> {
  let mut buffer = vec![0u8; 2]; // changed this for int16 sizing
  let mut wfs = vec![Vec::new(); channels];
  'outer: loop {
    for wf in wfs.iter_mut() {
      let bytes_read = input_buffer.read(&mut buffer).unwrap();
      if bytes_read == 0 {
        break 'outer;
      }
      let value = f64::from_le_bytes(buffer.as_slice().try_into().unwrap()); //Little endian
      wf.push(value);
    }
  }
  wfs
}
```

Leading to panic issue
<img width="1509" alt="Capture d’écran 2023-10-28 à 14 55 14" src="https://github.com/HEnquist/rubato/assets/7901366/cdcf726d-d6ef-415a-a82f-8e2ba03f175b">

I also tried a more complicated changed by re-writting the function to accept i16 

```rust
pub fn i16_reader_to_vecs<R: Read>(input_reader: &mut R, channels: usize) -> Vec<Vec<f64>> {
  let mut audio_data = Vec::with_capacity(channels);
  for _chan in 0..channels {
    audio_data.push(Vec::new());
  }
  'outer: loop {
    // dispatch the data between channels
    for audio_single_channel in audio_data.iter_mut() {
      match input_reader.read_i16::<LittleEndian>() {
        Ok(value_i16) => {
          let value_f64 = f64::from(value_i16);
          audio_single_channel.push(value_f64);
        }
        Err(err) => {
          break 'outer; // end of loop err happen when oef for eg
        }
      }
    }
  }
  audio_data
}

let mut read_buffer = Box::new(Cursor::new(&input_int16_array));
  let i16_data = i16_buffer_to_vecs(&mut read_buffer, 2);
  debug!(
    "It took {:?} to convert {} i16 elements vec to vec<vec<f64>> with [0] contains {} and [1] {}",
    convert_i16_time.elapsed(),
    input_int16_array.len(),
    i16_data[0].len(),
    i16_data[1].len()
  );

  let output_data = re_sample_audio_buffer(
    i16_data,
    sample_rate_input,
    sample_rate_output,
    channels,
    channels,
  );

//... then in  my main function for resample
  let mut buffer: Vec<u8> = Vec::with_capacity(output_data.len() * 2);

  for f64_value in output_data {
    let clamped = if f64_value >= i16::MIN as f64 && f64_value <= i16::MAX as f64 {
      f64_value as i16
    } else if f64_value < i16::MIN as f64 {
      i16::MIN
    } else {
      i16::MAX
    };

    // Split the data into two bytes of u8 for i16
    buffer.push((clamped >> 8) as u8);
    buffer.push((clamped & 0xFF) as u8);
  }
  
  // Then I write buffer to a file
  // Finally I execute the sox command to get back from .raw to .wav 
  // sox -e floating-point -L -b 64 -r 16000 -c 2 talk.raw -L -e signed-integer -b 16 talk-re-sample.wav
```

But no luck on this way too the sound is broken.

**Comment by HEnquist** [comment]
The second way looks good, it's probably just some silly little thing that prevents it from working properly.
I would add some prints to check that the samples are converted to and from float correctly. I would also use the to_le_bytes function instead of converting the i16 to u8 manually: https://doc.rust-lang.org/std/primitive.i16.html#method.to_le_bytes

Another thing, there is no reason do do the resampling with f64 precision. For i16 data, f32 is more than enough, and switching would make resampling a bit faster.

**Comment by MatthD** [comment]
ok thanks you for this information I used f64 because I add panic with f32 usage, will retry ;)

**Comment by MatthD** [comment]
@HEnquist Thanks for your help ,

So my difficulty was that in fact audio file need a range of [-1;1] and I was just converting int to float so it did no work.
I need to do

```rust
let data_f32 = f32::from_i16(value_i16).unwrap() / f32::from_i16(i16::MAX).unwrap();

//... then to go back to i16

re_sampled_f32_data
      .iter()
      .filter_map(|&f32_value| i16::from_f32(f32_value * f32::from_i16(i16::MAX).unwrap())) // if datatype on entry file was int16 we need to retransform to it
      .flat_map(|i| i.to_le_bytes())
```
