### ISSUE TITLE
asynchronous sampler crashes with access violation in fn interp_lin<T> when using chunksize of 1

### ISSUE THREAD

**Issue by nat3Github** [HEnquist/rubato#74]
i got a access violation exception calling resampler.process_into_buffer(&self.resampler_input, &mut self.resampler_output, Some(&self.channel_mask)) ;
using rubato = "0.14.1"
using FastFixedOut<f32> = FastFixedOut::new(96000.0/44100.0, 100.0, PolynomialDegree::Linear, 1, 8);
using  Resampler::input_buffer_allocate and Resampler::output_buffer_allocate(); methods to preallocate the io buffers.
this happened after a few successful calls to proccess_into_buffer() so i'm completely lost on what could be happening.
![image](https://github.com/HEnquist/rubato/assets/121395237/c9740b5e-a791-4c0e-ac46-72c75b0a0a06)
![image](https://github.com/HEnquist/rubato/assets/121395237/be5f258c-f4c5-4587-a52d-2b04945f118e)
![image](https://github.com/HEnquist/rubato/assets/121395237/60a3ceb6-b0d7-45e6-bb8b-fdb8bac6422e)

**Comment by nat3Github** [comment]
after testing this exception only occurs with a chunk_size of 1. if this isn't intended, here is a test to reproduce this error:

<code>
#[test]
fn test_rubato() {
    // new resampler
    let parameters = SincInterpolationParameters {
        sinc_len: 32, f_cutoff: 0.95, oversampling_factor: 32, interpolation: rubato::SincInterpolationType::Nearest, window: rubato::WindowFunction::Blackman
    };
    const CHUNK_SIZE:usize = 4;
    let resamplerx: SincFixedOut<f32> = rubato::SincFixedOut::new(44100.0/44100.0, 10.0, parameters,
        CHUNK_SIZE, 2).ok().unwrap();
    let mut resampler_input: Vec<Vec<f32>>= Resampler::input_buffer_allocate(&resamplerx, true);
    let mut resampler_output: Vec<Vec<f32>>= Resampler::output_buffer_allocate( &resamplerx, true);
    let mut resampler: SincFixedOut<f32> = resamplerx;


    let delay = Duration::from_micros(3);
    for _ in 0..4000 {
        sleep(delay);
        Resampler::process_into_buffer(&mut resampler, &resampler_input, &mut resampler_output, None).unwrap();
    }
}
<code/>

if this is intended then id be happy if an assertion or note in the docs is added. thank you

**Comment by HEnquist** [comment]
Thanks for the report!
Running with a chunksize of 1 will be extremely inefficient, so it's not something to recommend ever doing. But it should still work. I'll fix it in the next release.
Try to use a chunksize of at least 100 (ideally a bit larger, like 1000) if you want good performance.

**Comment by nat3Github** [comment]
my goal was sample accurate resampling related to resample ratio. but you're right thats probably overkill. nonetheless in my case chunksize has to be small in order to get low latency.

thank you for your work and quick response! :)

**Comment by HEnquist** [comment]
A fix is included in https://github.com/HEnquist/rubato/pull/78
