### ISSUE TITLE
Audio crackling

### ISSUE THREAD

**Issue by Tahinli** [HEnquist/rubato#83]
Hi, I decode audio file with symphonia and resample with rubato. If I decode all audio file then resample it, everything is perfect except time cost. As you know it takes time to decode the audio file. So I decided to decode and resample on the go, while listening. Firstly decoding itself has no problem but if I want to resample the audio data in every sample loop that syphonia does, audio starts cracking.

This is my decode code, if I use this in loop till the end there is no problem. But if I use sequentially with resampling, it's not good.

```rust
    let mut audio_decoded_left = vec![];
    let mut audio_decoded_right = vec![];
    let packet = match format.next_packet() {
        Ok(packet) => packet,
        Err(_) => return None,
    };

    while !format.metadata().is_latest() {
        format.metadata().pop();
    }

    if packet.track_id() != track_id {
        return None;
    }

    if let Ok(decoded) = decoder.decode(&packet) {
        if let AudioBufferRef::F32(buf) = decoded {
            for (left, right) in buf.chan(0).iter().zip(buf.chan(1).iter()) {
                audio_decoded_left.push(*left as f64);
                audio_decoded_right.push(*right as f64);
            }
        }
    }
    Some((audio_decoded_left, audio_decoded_right))
```
this is my resampling code.
```rust
    let params = SincInterpolationParameters {
        sinc_len: 256,
        f_cutoff: 0.95,
        interpolation: SincInterpolationType::Linear,
        oversampling_factor: 256,
        window: WindowFunction::BlackmanHarris2,
    };
    let mut resampler = SincFixedIn::<f64>::new(
        output_device_sample_rate as f64 / audio_sample_rate as f64,
        2.0,
        params,
        audio_decoded_left.len(),
        2,
    )
    .unwrap();

    let audio_decoded_channels_combined = vec![audio_decoded_left, audio_decoded_right];
    let audio_resampled = resampler
        .process(&audio_decoded_channels_combined, None)
        .unwrap();

    (audio_resampled[0].clone(), audio_resampled[1].clone())   
```

Here is how it sounds:

https://github.com/user-attachments/assets/e632d0c6-3686-41ed-ab0b-5e2c4bf9f725

Here is no-problem version that does full encoding first (It's slow :/):
https://github.com/Tahinli/radioxide/blob/c8ea82a3c178f63eaa5497e2441b66ecd2126b10/streamer/src/playing.rs#L119

**Comment by HEnquist** [comment]
Do you create a new resampler for every chunk? If yes that is why it doesn't work properly. The resampler does some buffering, so to process a stream in smaller chunks you need to use the same resampler instance all the way.
I haven't used Symphonia, does it produce fixed size chunks or do they vary?

**Comment by Tahinli** [comment]
> Do you create a new resampler for every chunk? If yes that is why it doesn't work properly. The resampler does some buffering, so to process a stream in smaller chunks you need to use the same resampler instance all the way. I haven't used Symphonia, does it produce fixed size chunks or do they vary?

Okay I'm now using same resampler with calculating chunk size one time this fixed crackling thanks. But this time another problem pops up. If audio bitrate is 128kbit it jumps samples.


https://github.com/user-attachments/assets/e3fed639-620c-43e3-80c1-65613d058485

```rust
fn decode_audio(
    format: &mut Box<dyn FormatReader>,
    track_id: u32,
    decoder: &mut Box<dyn Decoder>,
) -> Option<(Vec<f64>, Vec<f64>)> {
    let mut audio_decoded_left = vec![];
    let mut audio_decoded_right = vec![];
    let packet = match format.next_packet() {
        Ok(packet) => packet,
        Err(_) => return None,
    };

    while !format.metadata().is_latest() {
        format.metadata().pop();
    }

    if packet.track_id() != track_id {
        return None;
    }

    if let Ok(decoded) = decoder.decode(&packet) {
        if let AudioBufferRef::F32(buf) = decoded {
            for (left, right) in buf.chan(0).iter().zip(buf.chan(1).iter()) {
                audio_decoded_left.push(*left as f64);
                audio_decoded_right.push(*right as f64);
            }
        }
    }
    Some((audio_decoded_left, audio_decoded_right))
}

fn resample_audio(
    audio_decoded_left: Vec<f64>,
    audio_decoded_right: Vec<f64>,
    resampler: &mut SincFixedIn<f64>,
) -> (Vec<f64>, Vec<f64>) {
    let audio_decoded_channels_combined = vec![audio_decoded_left, audio_decoded_right];
    let audio_resampled = resampler
        .process(&audio_decoded_channels_combined, None)
        .unwrap();

    (audio_resampled[0].clone(), audio_resampled[1].clone())
}

async fn process_audio(
    output_device_sample_rate: u32,
    file: File,
    decoded_to_playing_sender: tokio::sync::broadcast::Sender<f32>,
) {
    let media_source_stream = MediaSourceStream::new(Box::new(file), Default::default());

    let hint = Hint::new();

    let metadata_options = MetadataOptions::default();
    let format_options = FormatOptions::default();

    let mut probed = symphonia::default::get_probe().format(
        &hint,
        media_source_stream,
        &format_options,
        &metadata_options,
    );

    match probed {
        Ok(probed_safe) => probed = Ok(probed_safe),
        Err(_) => return,
    }

    let mut format = probed.unwrap().format;

    let track = format
        .tracks()
        .iter()
        .find(|t| t.codec_params.codec != CODEC_TYPE_NULL)
        .unwrap();

    let audio_sample_rate = track.codec_params.sample_rate.unwrap();
    DecoderOptions::default();
    let decoder_options = DecoderOptions::default();
    let mut decoder = symphonia::default::get_codecs()
        .make(&track.codec_params, &decoder_options)
        .unwrap();

    let track_id = track.id;

    let params = SincInterpolationParameters {
        sinc_len: 256,
        f_cutoff: 0.95,
        interpolation: SincInterpolationType::Linear,
        oversampling_factor: 128,
        window: WindowFunction::BlackmanHarris2,
    };

    let chunk_size = match decode_audio(&mut format, track_id, &mut decoder) {
        Some((audio_decoded_left_channel, _)) => audio_decoded_left_channel.len(),
        None => return,
    };

    let mut resampler = SincFixedIn::<f64>::new(
        output_device_sample_rate as f64 / audio_sample_rate as f64,
        2.0,
        params,
        chunk_size,
        2,
    )
    .unwrap();

    loop {
        let (mut audio_decoded_left, mut audio_decoded_right) = (vec![], vec![]);

        match decode_audio(&mut format, track_id, &mut decoder) {
            Some((audio_decoded_left_channel, audio_decoded_right_channel)) => {
                for (single_left, single_right) in audio_decoded_left_channel
                    .iter()
                    .zip(&audio_decoded_right_channel)
                {
                    audio_decoded_left.push(*single_left);
                    audio_decoded_right.push(*single_right);
                }
            }
            None => break,
        };

        let (audio_resampled_left, audio_resampled_right) =
            resample_audio(audio_decoded_left, audio_decoded_right, &mut resampler);
        
        // This sends data to cpal for listening actually.
        for (single_left, single_right) in audio_resampled_left.iter().zip(&audio_resampled_right) {
            let _ = decoded_to_playing_sender.send(*single_left as f32);
            let _ = decoded_to_playing_sender.send(*single_right as f32);
        }
    }
}
```

**Comment by Tahinli** [comment]
I got new information. This only happens in release mod. Debug mod doesn't do this.

**Comment by HEnquist** [comment]
I have no idea what may be happening here. Sounds like pretty large chunks of audio are missing. Can you try to figure out at what stage it happens? Once the audio data reaches Rubato it has been decoded, so it doesn't make sense that the compressed bitrate would matter.

**Comment by Tahinli** [comment]
> I have no idea what may be happening here. Sounds like pretty large chunks of audio are missing. Can you try to figure out at what stage it happens? Once the audio data reaches Rubato it has been decoded, so it doesn't make sense that the compressed bitrate would matter.

I also couldn't understand why it's working in debug mode clearly but not release mode.

**Comment by HEnquist** [comment]
Release mode runs much (like 10x) faster than debug mode. Is it possible that the audio frames get ready too soon, and therefore get dropped? I would start by not ignoring the result of the two sends at the end (`let _ = decoded_to_playing_sender.send(*single_left as f32);`.
Ignoring `Result` is almost never a good idea.

**Comment by Tahinli** [comment]
> Release mode runs much (like 10x) faster than debug mode. Is it possible that the audio frames get ready too soon, and therefore get dropped? I would start by not ignoring the result of the two sends at the end (`let _ = decoded_to_playing_sender.send(*single_left as f32);`. Ignoring `Result` is almost never a good idea.

I tried and they're not returning errors.

**Comment by Tahinli** [comment]
> Ok then I would count audio frames and just print the values to the terminal. If you count the number of decoded frames, the number of resampled frames, the number sent to the playback loop, and the number consumed by the playback device, then you should get a better idea of where they go missing.

Thanks for the idea. Finally it's solved. My tokio channel size was small and this was causing the problem. Thanks a lot.
