### ISSUE TITLE
Check if my resampler usage is correct 

### ISSUE THREAD

**Issue by xd009642** [HEnquist/rubato#85]
So normally I'd use some closed source code making use of ffmpeg bindings to do audio resampling. But this is an open source project outside of my work so I thought I'd try rubato out as it seemed the most fleshed out solution. PR for reference https://github.com/xd009642/streamer-template/pull/19 

So initially I'm doing some fairly simple resamplings in the tests just as a sanity check before doing anything more complicated.

Also I've had to manually implement some truncation to cut off a trailing silence which i guess is based on the buffer size? It would be nice if this was documented in some way or there was a code sample. 

Hopefully my code is useful to see how someone with no knowledge of this library approaches using it and if there's any stupid mistakes I've made they could potentially be fed back into examples or docs to add more clarity.

EDIT: Removed something that was an issue in my test I fixed.

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by xd009642** [comment]
Managed to get it working as expected, feel free to check and see if I'm doing anything stupid but as it works hopefully I'm not :pray:

**Comment by HEnquist** [comment]
I took a quick look and I'd say it looks fine. But the resampler size looks a little odd, like a power of two with a typo: `const RESAMPLER_SIZE: usize = 4086;`. Was that supposed to be 4096? It doesn't matter for the performance of the chosen resampler but maybe a wrong value can cause trouble elsewhere.

**Comment by xd009642** [comment]
Ah yeah that was a typo. I was doing various powers of two and probably messed up in one of the changes.

It would be nice if I didn't have to manually figure out where to truncate to but that's do-able

**Comment by HEnquist** [comment]
You can use this to know how much to trim at the start: 
https://docs.rs/rubato/0.15.0/rubato/trait.Resampler.html#tymethod.output_delay
You'll still have to calculate how much to trim at the end. I don't see any reasonable way the library could help with this, considering that the ratio etc can be adjusted at any time while processing.
