### ISSUE TITLE
More sample types.

### ISSUE THREAD

**Issue by dvdsk** [HEnquist/rubato#87]
I am looking at rubato as a great improvement over the current fast but rather crude (linear) resampler in rodio.

Rodio's audio pipeline is generic over 3 different sample types: `i16`, `u16` and `f32`. The rubato docs mention that `f32` and `f64` are the only two types supported so far.  

Will that change in the future? 

Do the resampling techniques in rubato require floats? 

Thanks for your time and your very impressive resampler

Edit: I think I can answer my own question here: sine and cosine are not widely supported for integers (treating the whole integer range as -1 to 1). Since they are needed for the resampling algorithm only floats will work.

**Comment by HEnquist** [comment]
Yes the resamplers need to work on floats. Any integer format needs to be converted to float and then back to int afterwards. I'm working on making this easier, see https://github.com/HEnquist/rubato/issues/71#issuecomment-1780053242
It will take some time before that is finished though, so for now you will need to do the conversion yourself.
BTW Rubato doesn't need the floats to be in the -1.0 - 1.0 range so you don't need to scale the int values. A simple `value as f32` should do fine.
