### ISSUE TITLE
output_frames_next() returns the number including the margin of 10

### ISSUE THREAD

**Issue by AkiyukiOkayasu** [HEnquist/rubato#88]
I have noticed that FastFixedIn and SincFixedIn output_frames_next() always returns 10 more than the expected number.

https://github.com/HEnquist/rubato/blob/acca880e1afdd87dc0d9548676bcb1ca70d93407/src/asynchro_fast.rs#L449-L452

It says output_frames_max() contains a margin of 10 frames. It is understandable that output_frames_max(), which returns the maximum value, includes a margin.
https://github.com/HEnquist/rubato/blob/acca880e1afdd87dc0d9548676bcb1ca70d93407/src/asynchro_fast.rs#L443-L447

But why does the value returned by output_frames_next() include a margin?

**Comment by HEnquist** [comment]
> But why does the value returned by output_frames_next() include a margin?

It's because it is very difficult to calculate the exact number correctly, but the margin of 10 is somewhat arbitrarily chosen and can likely be reduced. The number is meant to be used to allocate an output buffer that is large enough. That should probably be mentioned in the docs.

**Comment by AkiyukiOkayasu** [comment]
This seems to be a documentation issue.  
The number of frames needed to calculate resampling and the number of frames included in the final output are two different issues, but the function name ‘output_frames_next()’ seems to indicate the latter.
Anyway, thank you for answering.

**Comment by HEnquist** [comment]
I have added a few words about this in the documentation for `output_frames_next`, will be included in the next release.

For later, it should be possible to make it an exact number also for the fixed input size resamplers. This would fit in nicely with some refactoring to make the fixed in and fixed out types share a lot more code.

**Comment by AkiyukiOkayasu** [comment]
Thank you for your quick support.

> For later, it should be possible to make it an exact number also for the fixed input size resamplers. This would fit in nicely with some refactoring to make the fixed in and fixed out types share a lot more code.

I think it's very great. This is particularly useful in environments with tight memory constraints, such as embedded systems.  

This issue has been resolved and I would like to close it. Thank you very much.
