### ISSUE TITLE
delay in `Resampler::output_delay()`

### ISSUE THREAD

**Issue by daniellga** [HEnquist/rubato#90]
Hi! Would you mind documenting in this function what is the delay it refers to? Thanks!

**Comment by HEnquist** [comment]
I added one more line here, does it help?
https://github.com/HEnquist/rubato/blob/55008a5d21073b871c82f30a0a9ab6f7980da65e/src/lib.rs#L242

**Comment by daniellga** [comment]
`/// This gives how many frames any event in the input is delayed before it appears in the output.`

This one helps a lot. Thanks! I was having a hard time understanding what was the delay definition here.
