### ISSUE TITLE
Reported output delay of FFT based resamplers not correct

### ISSUE THREAD

**Issue by steckes** [HEnquist/rubato#96]
Hey Henrik!

I want to use rubato in an audio plugin and need to report the right delay to the DAW so it can be compensated. Doing this I noticed, that when the resampling is active, the delay is not correct.

For testing, I was running an impulse through the FFTFixedOut resampler and loaded the impulse response with the Pyfar package in Python to calculate the precise delay of the impulse response.

```rust
#[test]
fn export_impulse_response() {
    let num_frames = 512;

    let output_sample_rate = 192_000;
    let mut resampler = FftFixedOut::new(48_000, output_sample_rate, num_frames, 1, 1).unwrap();

    let mut impulse = vec![0.0; resampler.input_frames_next()];
    impulse[0] = 1.0;

    let output = resampler.process(&[impulse], None).unwrap();

    dbg!(resampler.output_delay()); // reporting 256 frames delay

    // export
    let waveform = babycat::Waveform::new(output_sample_rate as u32, 1, output[0].clone());
    waveform.to_wav_file("impulse_response.wav").unwrap();
}
```

```python
import pyfar

impulse_response = pyfar.io.read_audio("impulse_response.wav")
delay = pyfar.dsp.find_impulse_response_delay(impulse_response=impulse_response)
print(delay) # reporting 247.75 frames delay
```

For the case the input and output samplerates are equal, the latency is correct (fft_size / 2), for the case the output samplerate is higher the actual latency is lower, for the case the output samplerate is lower, the actual latency is higher than the reported one.

I know that the sinc filter delay should not be dependent on the resampling ratio, but where is the ratio dependent delay coming from?

**Comment by HEnquist** [comment]
The sinc filter is the same length as the FFT, that's how the delay gets dependent on the ratio. How much off are the delay values? Is it always a handful of frames like 247 instead of 256?

**Comment by HEnquist** [comment]
I would also be interested in how the waveform in "impulse_response.wav" looks between frame 220 - 270 or so.

**Comment by steckes** [comment]
This is the impulse response:
![image](https://github.com/user-attachments/assets/16eb4777-f8b4-4483-9625-66818682b2cd)

Here are some extreme ranges:

# FftFixedOut

| From kHz | to kHz | Offset samples |
|--------|--------|--------|
| 8 | 192 | 64 |
| 16 | 192 | 34 |
| 16 | 48 | 9 |
| 192 | 8 | 0 |
| 48 | 16 | 0 |

# FftFixedIn

| From kHz | to kHz | Reported Delay | Is Delay |
|--------|--------|--------|
| 8 | 192 | 6144 | 6093 |
| 16 | 192 | 3072 | 3047 |
| 16 | 48 | 768 | 762 | 
| 192 | 8 | 11 | 10 |
| 48 | 16 | 85 | 85 |

So it seems that downsampling mostly works fine, while the problem is in upsampling.

Let me know if I can analyze something else or you need a better view on the IR.

**Comment by HEnquist** [comment]
The impulse response actually looks alright. 256 frames at 192 kHz is 1.33 ms and that is where the main peak appears to be. 247 as reported by pyfar is 1.28 ms. That would put the peak closer to the 1.2 ms grid line than the 1.4 ms one. 
So for this one it looks like pyfar reports an incorrect delay. Can you check that for a few more examples? And can you can show frames instead of time on the x axis?

**Comment by steckes** [comment]
You are absolutely right, the reported latency from pyfar is not correct.

Here we have the IR that was reported right by pyfar (192 -> 8):

![image](https://github.com/user-attachments/assets/8d6f279f-d585-491a-9464-54326ff40257)

Here we have the IR where pyfar is not right (8 -> 192):

![image](https://github.com/user-attachments/assets/d8564186-aeab-4396-a57b-b0f46194a0b1)

I will close this issue now, thank you for looking into it with me!

**Comment by HEnquist** [comment]
If you have the time, maybe you could report these incorrect results to the pyfar maintainers?
